version: 2
registries:
  docker-elastic:
    type: docker-registry
    url: https://docker.elastic.co
    username: ${{secrets.DOCKER_USERNAME}}
    password: ${{secrets.DOCKER_PASSWORD}}

updates:

  # GitHub actions
  - package-ecosystem: github-actions
    directories:
      - '/'
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - '/'
    registries: "*"
    schedule:
      interval: "daily"
