name: release
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1-23 * * 1-5'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "My_Super_Secret_Password"
