name: test-annotations
on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '0 1-23 * * 1-5'

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: yuzutech/annotations-action@v0.5.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title: 'lint'
        input: ./json-report.json